INSERT INTO `building` (`id`, `name`) VALUES
("1", "Kaufman Hall"),
("2", "Public Affairs Building"),
("3", "Broad Art Center"),
("4", "Kinsey Science Teaching Pavilion"),
("5", "Student Activities Center"),
("6", "Dodd Hall"),
("7", "Botany Building"),
("8", "La Kretz Hall"),
("9", "School of Dentistry"),
("10", "Fowler Museum at UCLA"),
("11", "Renee and David Kaplan Hall"),
("12", "Haines Hall"),
("13", "Rolfe Hall"),
("14", "Boelter Hall"),
("15", "Life Sciences"),
("16", "Education and Information Studies Building"),
("17", "Boyer Hall"),
("18", "Bunche Hall"),
("19", "De Neve Plaza Commons Building"),
("20", "Royce Hall"),
("21", "Moore Hall"),
("22", "Young Hall"),
("23", "Biomedical Sciences Research Building"),
("24", "School of Public Health"),
("25", "Center for the Health Sciences"),
("26", "Physics and Astronomy Building"),
("27", "Knudsen Hall"),
("28", "Mathematical Sciences"),
("29", "Schoenberg Music Building"),
("30", "Semel Institute for Neuroscience and HumanBehavior"),
("31", "Powell Library Building"),
("32", "Perloff Hall"),
("33", "Young Research Library"),
("34", "Franz Hall"),
("35", "Geology Building"),
("36", "Gold Hall"),
("37", "Engineering V"),
("38", "Law Building"),
("39", "Cornell Hall"),
("40", "Entrepreneurs Hall"),
("41", "Orthopaedic Hospital Research Center"),
("42", "Molecular Sciences Building"),
("43", "Gonda (Goldschmied) Neuroscience and Genetics Research Center"),
("44", "Engineering IV"),
("45", "La Kretz Garden Pavilion"),
("46", "Campbell Hall"),
("47", "Factor Health Sciences Building"),
("48", "Melnitz Hall"),
("49", "Macgowan Hall East"),
("50", "Macgowan Hall");